### ISSUE TITLE
Building with -D DIAG=1 fails on MacOS Mojave

### ISSUE THREAD

**Issue by elzoido238** [dpiparo/vdt#9]
Building with the `cmake` option `-D DIAG=1` fails on MacOS Mojave with many "no matching constructor" errors originating from [`vdtdiag_fcnTuples.h`](https://github.com/dpiparo/vdt/tree/master/include/diagnostic/vdtdiag_fcnTuples.h) (see attached output below).

[cmake_out.txt](https://github.com/dpiparo/vdt/files/2830140/cmake_out.txt)
[make_out.txt](https://github.com/dpiparo/vdt/files/2830141/make_out.txt)

**Comment by dpiparo** [comment]
thanks. Looking into it.

**Comment by dpiparo** [comment]
this has been fixed and a new release created: https://github.com/dpiparo/vdt/releases/tag/v0.4.3
thanks a lot for reporting!

**Comment by elzoido238** [comment]
You're welcome! Thanks for the quick response!
